name: Compilation

on: [push, pull_request]

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal

      - uses: ./
        with:
          workspaces: tests

      - run: |
          cargo check
          cargo test
        working-directory: tests
